mutation updateToken($id: Int!, $name: String!, $launch: DateTime) {
  updateToken(
    updateTokenInput: {
      id: $id
      name: $name
      launch: $launch
    }) {
    id
    name
    launch
  }
}